In [1]:
# pip install raptor_functions
from raptor_functions.raptor_data import load_validated_breath_dataset

df = load_validated_breath_dataset()
df.head()

,unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid

,unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid