In [1]:
from raptor_functions import raptor_data

In [2]:
from raptor_data import load_validated_breath_dataset

In [3]:
load_validated_breath_dataset()

,unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,137,57b,148.0,316.236,316.021,316.021,313.514,312.154,315.759,316.117,...,103.500,103.261,103.548,27.065,flush,20/01/2022,37.00,2022-01-20 16:13:32.000,57b_16_12_08.03.txt,Control
149,137,57b,149.0,316.833,315.902,316.403,313.777,311.987,315.711,316.308,...,103.595,103.357,103.548,32.524,flush,20/01/2022,37.25,2022-01-20 16:13:32.250,57b_16_12_08.03.txt,Control
150,137,57b,150.0,316.714,316.188,315.973,313.801,312.345,315.400,315.687,...,103.500,103.404,103.404,41.007,flush,20/01/2022,37.50,2022-01-20 16:13:32.500,57b_16_12_08.03.txt,Control
151,137,57b,151.0,316.809,315.711,315.615,313.968,312.106,316.403,316.475,...,103.452,103.428,103.619,49.128,flush,20/01/2022,37.75,2022-01-20 16:13:32.750,57b_16_12_08.03.txt,Control
152,137,57b,152.0,316.117,315.997,315.973,313.705,311.819,315.353,315.973,...,103.452,103.261,103.404,53.324,flush,20/01/2022,38.00,2022-01-20 16:13:33.000,57b_16_12_08.03.txt,Control

In [1]:
from raptor_data import load_data

In [2]:
load_data()

,unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,137,57b,148.0,316.236,316.021,316.021,313.514,312.154,315.759,316.117,...,103.500,103.261,103.548,27.065,flush,20/01/2022,37.00,2022-01-20 16:13:32.000,57b_16_12_08.03.txt,Control
149,137,57b,149.0,316.833,315.902,316.403,313.777,311.987,315.711,316.308,...,103.595,103.357,103.548,32.524,flush,20/01/2022,37.25,2022-01-20 16:13:32.250,57b_16_12_08.03.txt,Control
150,137,57b,150.0,316.714,316.188,315.973,313.801,312.345,315.400,315.687,...,103.500,103.404,103.404,41.007,flush,20/01/2022,37.50,2022-01-20 16:13:32.500,57b_16_12_08.03.txt,Control
151,137,57b,151.0,316.809,315.711,315.615,313.968,312.106,316.403,316.475,...,103.452,103.428,103.619,49.128,flush,20/01/2022,37.75,2022-01-20 16:13:32.750,57b_16_12_08.03.txt,Control
152,137,57b,152.0,316.117,315.997,315.973,313.705,311.819,315.353,315.973,...,103.452,103.261,103.404,53.324,flush,20/01/2022,38.00,2022-01-20 16:13:33.000,57b_16_12_08.03.txt,Control

In [4]:
from pathlib import Path
from subprocess import check_output

In [19]:
 if not Path('../pyproject.toml').exists():
        raise Exception(f"Cannot find a `pyproject.toml` file in the current folder: {Path().resolve()}")
project_name, version = check_output(("poetry", "version")).strip().decode().split(' ')
print(version)

0.0.4

In [18]:
# pip install raptor_functions
from raptor_data import load_validated_breath_dataset
df = load_validated_breath_dataset()
df.head()

,unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid

In [20]:
from raptor_function import load_validated_breath_dataset
df = load_validated_breath_dataset()

ModuleNotFoundError: No module named 'raptor_function'

In [21]:
df

,unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,137,57b,148.0,316.236,316.021,316.021,313.514,312.154,315.759,316.117,...,103.500,103.261,103.548,27.065,flush,20/01/2022,37.00,2022-01-20 16:13:32.000,57b_16_12_08.03.txt,Control
149,137,57b,149.0,316.833,315.902,316.403,313.777,311.987,315.711,316.308,...,103.595,103.357,103.548,32.524,flush,20/01/2022,37.25,2022-01-20 16:13:32.250,57b_16_12_08.03.txt,Control
150,137,57b,150.0,316.714,316.188,315.973,313.801,312.345,315.400,315.687,...,103.500,103.404,103.404,41.007,flush,20/01/2022,37.50,2022-01-20 16:13:32.500,57b_16_12_08.03.txt,Control
151,137,57b,151.0,316.809,315.711,315.615,313.968,312.106,316.403,316.475,...,103.452,103.428,103.619,49.128,flush,20/01/2022,37.75,2022-01-20 16:13:32.750,57b_16_12_08.03.txt,Control
152,137,57b,152.0,316.117,315.997,315.973,313.705,311.819,315.353,315.973,...,103.452,103.261,103.404,53.324,flush,20/01/2022,38.00,2022-01-20 16:13:33.000,57b_16_12_08.03.txt,Control

In [8]:
import pandas as pd
url = 'https://drive.google.com/file/d/1LUBsw5nIW_VSDGucxeudCrzDy4ntC1gW/view?usp=sharing'
# url='https://drive.google.com/file/d/0B6GhBwm5vaB2ekdlZW5WZnppb28/view?usp=sharing'
url='https://drive.google.com/uc?id=' + url.split('/')[-2]
df = pd.read_csv(url, index_col=0)

In [9]:
df

,unique_id,exp_name,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,...,sensor_22,sensor_23,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp,filename,result
0,0,39A,0.0,316.594,315.854,315.735,313.180,307.498,315.926,316.188,...,103.786,103.404,103.691,52.467,baseline,20/01/2022,0.00,2022-01-20 13:31:47.000,39A_13_31_00.03.txt,Covid
1,0,39A,1.0,316.928,315.854,316.188,313.324,307.331,315.997,316.499,...,103.882,103.357,103.595,45.112,baseline,20/01/2022,0.25,2022-01-20 13:31:47.250,39A_13_31_00.03.txt,Covid
2,0,39A,2.0,315.711,316.045,315.759,313.514,307.403,315.950,315.926,...,104.001,103.452,103.643,35.637,baseline,20/01/2022,0.50,2022-01-20 13:31:47.500,39A_13_31_00.03.txt,Covid
3,0,39A,3.0,316.499,315.854,315.329,312.536,308.095,315.854,316.403,...,104.073,103.380,103.619,28.102,baseline,20/01/2022,0.75,2022-01-20 13:31:47.750,39A_13_31_00.03.txt,Covid
4,0,39A,4.0,317.048,315.568,315.520,312.679,307.188,315.926,316.451,...,103.929,103.357,103.428,26.794,baseline,20/01/2022,1.00,2022-01-20 13:31:48.000,39A_13_31_00.03.txt,Covid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,137,57b,148.0,316.236,316.021,316.021,313.514,312.154,315.759,316.117,...,103.500,103.261,103.548,27.065,flush,20/01/2022,37.00,2022-01-20 16:13:32.000,57b_16_12_08.03.txt,Control
149,137,57b,149.0,316.833,315.902,316.403,313.777,311.987,315.711,316.308,...,103.595,103.357,103.548,32.524,flush,20/01/2022,37.25,2022-01-20 16:13:32.250,57b_16_12_08.03.txt,Control
150,137,57b,150.0,316.714,316.188,315.973,313.801,312.345,315.400,315.687,...,103.500,103.404,103.404,41.007,flush,20/01/2022,37.50,2022-01-20 16:13:32.500,57b_16_12_08.03.txt,Control
151,137,57b,151.0,316.809,315.711,315.615,313.968,312.106,316.403,316.475,...,103.452,103.428,103.619,49.128,flush,20/01/2022,37.75,2022-01-20 16:13:32.750,57b_16_12_08.03.txt,Control
152,137,57b,152.0,316.117,315.997,315.973,313.705,311.819,315.353,315.973,...,103.452,103.261,103.404,53.324,flush,20/01/2022,38.00,2022-01-20 16:13:33.000,57b_16_12_08.03.txt,Control

In [3]:
from datasets import get_data